-- HRMS Enums
CREATE TYPE user_role AS ENUM ('ADMIN', 'HR', 'EMPLOYEE');
CREATE TYPE employment_type AS ENUM ('FULL_TIME', 'PART_TIME', 'CONTRACT');
CREATE TYPE work_mode AS ENUM ('HYBRID', 'OFFICE_ONLY', 'WFH_ALLOWED');
CREATE TYPE work_mode_detected AS ENUM ('OFFICE', 'WFH', 'UNKNOWN');
CREATE TYPE attendance_status AS ENUM (
  'PRESENT', 'WFH', 'ABSENT', 'LEAVE', 'HOLIDAY',
  'WEEKEND', 'HALF_DAY', 'LATE', 'NON_COMPLIANT'
);
CREATE TYPE attendance_event_type AS ENUM (
  'CHECK_IN', 'CHECK_OUT', 'PING', 'IDLE_START', 'IDLE_END', 'LOCATION_UPDATE'
);
CREATE TYPE leave_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');
CREATE TYPE leave_approval_flow AS ENUM ('MANAGER_THEN_HR', 'HR_ONLY', 'MANAGER_ONLY');
CREATE TYPE accrual_frequency AS ENUM ('MONTHLY', 'YEARLY');
CREATE TYPE payroll_run_status AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');
CREATE TYPE moderation_status AS ENUM ('PENDING', 'APPROVED', 'FLAGGED');
